site_name: FRAME Online
repo_url: https://github.com/burespe1/FRAME-online
site_url: https://burespe1.github.io/FRAME-online
repo_name: FRAME-online
theme:
  logo: assets/frame-logo.png
  name: material
  palette: 
    # Palette toggle for light mode
    - primary: teal
      accent: light green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  
nav:
  - Home: index.md
  - "Getting Started":
      - "FRAME Architecture": getting-started/frame-architecture.md
      - In a Nutshell: getting-started/in-a-nutshell.md
      - FRAME Architecture Tool: getting-started/tool.md
      - User Guide: getting-started/user-guide.md
  - "Reference Architectures":
      - ITS Directives: reference-architectures/its-directives.md
  - Downloads:
      - Articles & Reports: downloads/articles-related-reports.md
      - FRAME Architecture 4.1: downloads/frame-architecture-4-1.md
      - FRAME Architecture 5.1: downloads/frame-architecture-5-1.md
  - Projects:
      - Frame-NEXT: projects/frame-next.md
  - Forum:
      - Objectives: forum/objectives.md
      - Services: forum/services.md 
  - About: about.md
  - FAQs: faq.md

markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - macros
