site_name: FRAME Online
repo_url: https://github.com/burespe1/FRAME-online
site_url: https://burespe1.github.io/FRAME-online
repo_name: FRAME-online
theme:
  logo: assets/img/frame-logo.png
  name: material
  icon:
    annotation: material/arrow-right-circle
  palette: 
    # Palette toggle for light mode
    - primary: teal
      accent: light green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  
nav:
  - Home: index.md
  - "Getting Started":
      - "What is Architecture": getting-started/in-a-nutshell.md
      - "FRAME Architecture": getting-started/frame-architecture.md
      - FRAME Tool: getting-started/tool.md
      - User Guide: getting-started/user-guide.md
  - FRAME Models:
      - FRAME Architecture v5: model/frame-architecture-5.md
      - FRAME Architecture v4: model/frame-architecture-4.md
      - Reference Architectures: model/reference-architectures.md
  - Downloads:
      - "Documents & Methodologies": downloads/documents-and-methodologies.md
      - "Articles & Reports": downloads/articles-related-reports.md
  - Projects:
      - FRAME-NEXT: projects/frame-next.md 
  - About: 
      - Impressum: about.md
      - FAQs: faq.md
  - Parked:
      - ITS Directives: unused/its-directives.md
      - Old index: unused/old-index.md
      - Objectives: unused/objectives.md
      - Services: unused/services.md 
      

markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - macros